# Generated by Django 4.1 on 2023-06-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_product_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pred_label_json",
        ),
    ]
