# Generated by Django 4.1 on 2023-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_product_pred_label_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pred_label_json",
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
