# Generated by Django 4.1 on 2023-04-26 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_product_pred_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pred_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date publish"
            ),
            preserve_default=False,
        ),
    ]
