# Generated by Django 4.1 on 2023-04-28 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_product_pred_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pred_label_text",
            field=models.CharField(default="numm", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="pred_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date publish"
            ),
        ),
    ]
