# Generated by Django 4.1 on 2023-04-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_product_pred_label_text_alter_product_pred_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pred_label_text",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
