# Generated by Django 4.1 on 2023-04-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_product_pred_label_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pred_label_text",
            field=models.CharField(default="", max_length=200),
        ),
    ]
